server {
    listen 443 ssl;
    server_name chrms.chirocity.gov.et;
    ssl_certificate /etc/letsencrypt/live/chrms.chirocity.gov.et/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/chrms.chirocity.gov.et/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    client_max_body_size 10m;
    resolver 127.0.0.11 valid=10s ipv6=off;
    location / {
        set $chrms_upstream http://chrms-web:80;
        proxy_pass $chrms_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 443 ssl;
    server_name chrms-api.chirocity.gov.et;
    ssl_certificate /etc/letsencrypt/live/chrms.chirocity.gov.et/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/chrms.chirocity.gov.et/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    client_max_body_size 10m;
    resolver 127.0.0.11 valid=10s ipv6=off;
    location / {
        set $chrms_upstream http://chrms-api:3000;
        proxy_pass $chrms_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
